export const SET_QUESTIONS = 'SET_QUESTIONS' ;
export const SAVE_NEW_QUESTION = 'SAVE_NEW_QUESTION' ;

export const SET_USERS = 'SET_USERS' ;
export const SAVE_QUESTION_ANSWER = 'SAVE_QUESTION_ANSWER' ;