export const GET_QUESTIONS = 'GET_QUESTIONS' ;
export const SAVE_NEW_QUESTION = 'SAVE_NEW_QUESTION' ;

export const GET_USERS = 'GET_USERS' ;
export const SAVE_QUESTION_ANSWER = 'SAVE_QUESTION_ANSWER' ;